name: application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image: ^4.2.0
  loading_indicator: ^3.1.1
  provider: ^6.1.2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: KairosPro
      fonts:
        - asset: fonts/KairosProExtendedMedium.ttf
    - family: TrajanPro
      fonts:
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
